import { useState } from 'react'
import { ToolLayout } from '@/components/tool/ToolLayout'
import { ToolInput } from '@/components/tool/ToolInput'
import { ToolOutput } from '@/components/tool/ToolOutput'
import { ToolOptions } from '@/components/tool/ToolOptions'
import { Button } from '@/components/ui/Button'
import { Toggle } from '@/components/ui/Toggle'
import { useTool } from '@/hooks/useTool'
import { Play, Trash2, Box } from 'lucide-react'

type Language = 'Java' | 'Go' | 'Rust' | 'Python' | 'C#'

export default function JsonToStruct() {
    const { output, setOutput, clearOutput } = useTool('json-to-struct')
    const [input, setInput] = useState(output?.input ?? '')
    const [lang, setLang] = useState<Language>('Java')
    const [rootName, setRootName] = useState('Autogenerated')
    const [error, setError] = useState('')

    const generate = () => {
        setError('')
        if (!input.trim()) return
        try {
            const obj = JSON.parse(input)
            let result = ''
            if (lang === 'Java') result = generateJava(obj, rootName)
            else if (lang === 'Go') result = generateGo(obj, rootName)
            else if (lang === 'Rust') result = generateRust(obj, rootName)
            else if (lang === 'Python') result = generatePython(obj, rootName)
            else if (lang === 'C#') result = generateCSharp(obj, rootName)
            
            setOutput({ input, output: result })
        } catch (e) {
            setError('Invalid JSON: ' + (e as Error).message)
        }
    }

    const clear = () => { setInput(''); clearOutput(); setError('') }

    return (
        <ToolLayout toolId="json-to-struct">
            <ToolInput value={input} onChange={setInput} placeholder="Paste JSON here..." />
            <ToolOptions>
                <div className="tool-option-group">
                    <label>Target Language</label>
                    <Toggle options={['Java', 'Go', 'Rust', 'Python', 'C#']} value={lang} onChange={v => setLang(v as Language)} />
                </div>
                <div className="tool-option-group">
                    <label>Root Class Name</label>
                    <input 
                        className="dt-input" 
                        value={rootName} 
                        onChange={e => setRootName(e.target.value)} 
                        placeholder="e.g. User"
                        style={{ background: 'var(--color-bg-input)', border: '1px solid var(--color-border)', borderRadius: '4px', padding: '4px 8px', color: 'var(--color-text-primary)' }}
                    />
                </div>
            </ToolOptions>
            <div className="tool-actions">
                <Button onClick={generate} icon={<Play size={13} />}>Generate</Button>
                <Button variant="danger" onClick={clear} icon={<Trash2 size={13} />}>Clear</Button>
            </div>
            {error && <div style={{ color: 'var(--color-danger)', fontSize: 13, marginTop: 10 }}>{error}</div>}
            <ToolOutput fields={[{ label: `${lang} Model`, value: typeof output?.output === 'string' ? output.output : '' }]} />
        </ToolLayout>
    )
}

function generateJava(obj: any, name: string): string {
    let code = `@Data\npublic class ${name} {\n`
    Object.entries(obj).forEach(([k, v]) => {
        let type = 'Object'
        if (typeof v === 'string') type = 'String'
        else if (typeof v === 'number') type = Number.isInteger(v) ? 'Integer' : 'Double'
        else if (typeof v === 'boolean') type = 'Boolean'
        else if (Array.isArray(v)) type = 'List<Object>'
        else if (v && typeof v === 'object') type = k.charAt(0).toUpperCase() + k.slice(1)
        code += `    private ${type} ${k};\n`
    })
    code += '}'
    return code
}

function generateGo(obj: any, name: string): string {
    let code = `type ${name} struct {\n`
    Object.entries(obj).forEach(([k, v]) => {
        let type = 'interface{}'
        if (typeof v === 'string') type = 'string'
        else if (typeof v === 'number') type = Number.isInteger(v) ? 'int' : 'float64'
        else if (typeof v === 'boolean') type = 'bool'
        const goName = k.charAt(0).toUpperCase() + k.slice(1)
        code += `    ${goName} ${type} \`json:"${k}"\`\n`
    })
    code += '}'
    return code
}

function generateRust(obj: any, name: string): string {
    let code = `#[derive(Serialize, Deserialize)]\npub struct ${name} {\n`
    Object.entries(obj).forEach(([k, v]) => {
        let type = 'Value'
        if (typeof v === 'string') type = 'String'
        else if (typeof v === 'number') type = Number.isInteger(v) ? 'i64' : 'f64'
        else if (typeof v === 'boolean') type = 'bool'
        code += `    pub ${k}: ${type},\n`
    })
    code += '}'
    return code
}

function generatePython(obj: any, name: string): string {
    let code = `from dataclasses import dataclass\n\n@dataclass\nclass ${name}:\n`
    Object.entries(obj).forEach(([k, v]) => {
        let type = 'Any'
        if (typeof v === 'string') type = 'str'
        else if (typeof v === 'number') type = Number.isInteger(v) ? 'int' : 'float'
        else if (typeof v === 'boolean') type = 'bool'
        code += `    ${k}: ${type}\n`
    })
    return code
}

function generateCSharp(obj: any, name: string): string {
    let code = `public class ${name}\n{\n`
    Object.entries(obj).forEach(([k, v]) => {
        let type = 'object'
        if (typeof v === 'string') type = 'string'
        else if (typeof v === 'number') type = Number.isInteger(v) ? 'int' : 'double'
        else if (typeof v === 'boolean') type = 'bool'
        const csName = k.charAt(0).toUpperCase() + k.slice(1)
        code += `    public ${type} ${csName} { get; set; }\n`
    })
    code += '}'
    return code
}
